source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "redis", "~> 5.2"
gem "connection_pool", "~> 2.5.4"
gem "sidekiq", "~> 7.3"
gem "propshaft"
gem "jsbundling-rails"
gem "cssbundling-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "rack-cors"

gem "devise"
gem "omniauth-google-oauth2"
gem "pundit"

gem "spree", "~> 4.7"
gem "spree_auth_devise", "~> 4.6.3"

gem "stripe", "~> 12.0"
gem "shopify_api", "~> 13.0"
gem "resend", "~> 0.8"
gem "httparty"
gem "oj"
gem "pgvector", "~> 0.3.3"

gem "bootsnap", require: false

group :development, :test do
  gem "dotenv-rails"
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "database_cleaner-active_record"
  gem "climate_control"
end

group :development do
  gem "web-console"
  gem "listen"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "shoulda-matchers"
end
